### ISSUE TITLE
Display problems with mobile/small screen

### ISSUE THREAD

**Issue by TrumanRu** [kenan3008/redmine_issue_view_columns#2]
Steps to reproduce:

1. Open issue with related/sub tasks
2. Resize browser window to less than 900px
3. Both lists are adapted but looks so thin

It's because of table's headers.

I've cured it by CSS (used `View Customize plugin`):
```
@media screen and (max-width: 899px) {
  table.list.issues > tbody > tr:first-child {
    display: none;
  }
}
```

**Comment by kenan3008** [comment]
Thanks for the info about this. I'll test and push the code :)

**Comment by kenan3008** [comment]
added in 4c11bdd
