### ISSUE TITLE
Some issues doesn't open with error "undefined local variable or method `link_to_context_menu' "

### ISSUE THREAD

**Issue by TrumanRu** [kenan3008/redmine_issue_view_columns#3]
Most issues open OK.
But some issues (I'll try to find same attributes) don't open with error.

**production.log**
```
Started GET "/redmine/issues/20" for 192.168.115.2 at 2019-05-06 15:25:02 +0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"20"}
  Current user: username (id=5)
  Rendered issues/_action_menu.html.erb (334.6ms)
  Rendered plugins/scrum/app/views/scrum_hooks/issues/_show.html.erb (92.3ms)
  Rendered plugins/redmine_issue_tabs/app/views/redmine_issue_tabs/_blank.html.erb (1.1ms)
  Rendered common/_tabs.html.erb (23.4ms)
  Rendered plugins/redmine_issue_tabs/app/views/hooks/redmine_issue_tabs/_rm_history_tabs.html.erb (62.6ms)
  Rendered plugins/unread_issues/app/views/hooks/unread_isues/_issue_bottom_details.html.erb (3.3ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (40.8ms)
  Rendered issues/_relations.html.erb (949.1ms)
  Rendered issues/show.html.erb within layouts/base (2742.3ms)
Completed 500 Internal Server Error in 3773ms (ActiveRecord: 172.9ms)

ActionView::Template::Error (undefined local variable or method `link_to_context_menu' for #<#<Class:0x000055acd8c85c50>:0x000055acd8ca8930>
Did you mean?  link_to_unless_current):
     8: 
     9: <% if @relations.present? %>
    10: <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
    11:   <%= render_issue_relations(@issue, @relations) %>
    12: <% end %>
    13: <% end %>
    14: 
  plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:84:in `block in render_issue_relations'
  plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:63:in `each'
  plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:63:in `render_issue_relations'
  app/views/issues/_relations.html.erb:11:in `block in _0e8864e1f4954ccb9c2558b0b303beb3'
  app/views/issues/_relations.html.erb:10:in `_0e8864e1f4954ccb9c2558b0b303beb3'
  plugins/redmine_workflow_enhancements/lib/workflow_enhancements/patches/action_view_rendering.rb:53:in `render_with_workflow_enhancements'
  app/views/issues/show.html.erb:127:in `_051ece3abb829413f4ce985b048b0721'
  app/controllers/issues_controller.rb:106:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:99:in `show'
  plugins/a_common_libs/lib/acl/patches/controllers/issues_controller_patch.rb:15:in `show_with_acl'
  plugins/redmine_issue_tabs/lib/redmine_issue_tabs/issues_controller_patch.rb:32:in `show_with_rit'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Processing by UsErrorsController#error_500 as HTML
  Parameters: {"id"=>"20"}
  Current user: username (id=5)
  Rendered plugins/usability/app/views/errors/error_status.html.erb (14.8ms)
Completed 500 Internal Server Error in 38ms (Views: 23.0ms | ActiveRecord: 7.0ms)
```

**Comment by kenan3008** [comment]
Could you please give me the Redmine version you're using?

**Comment by TrumanRu** [comment]
```
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.3.7-p456 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.10.2
  Git                            2.19.1
  Filesystem                     
  GitMirror                      2.19.1
Redmine plugins:
  a_common_libs                  2.5.3
  custom_menu                    1.8.5
  easy_mindmup                   1.0
  easy_wbs                       1.5
  extra_queries                  2.3.5
  global_roles                   2.2.4
  redmine_attribute_quickies     1.0.2
  redmine_base_deface            0.0.1
  redmine_better_overview        1.0.0
  redmine_checklists             3.1.11
  redmine_custom_workflows       0.1.6
  redmine_default_custom_query   1.3.0
  redmine_edit_custom_fields     0.0.5
  redmine_editor_preview_tab     0.1.5
  redmine_gemavatar              1.1
  redmine_git_mirror             0.8.0
  redmine_inline_auto_complete   0.1.0
  redmine_issue_tabs             1.3.2
  redmine_merge_request_links    2.1.1
  redmine_more_code              1.0.0
  redmine_more_context           1.0.0
  redmine_my_page                0.1.13
  redmine_workflow_enhancements  0.5.0
  redmine_xlsx_format_issue_exporter 0.1.6
  scrum                          0.18.0
  that_email_log                 0.0.2
  unread_issues                  2.2.3
  usability                      2.3.9
  view_customize                 2.1.0
```

**Comment by TrumanRu** [comment]
Additional info.
The issue (issue/20) has link "Copied to Feature <issue number>".

May be the problem because of an issue link type?

**Comment by skillvrn** [comment]
I have the same problem:

Started GET "/issues/2276" for 10.1.100.5 at 2019-06-07 09:07:54 +0300
Processing by IssuesController#show as HTML
  Parameters: {"id"=>"2276"}
  Current user: sk (id=5)
  Rendered issues/_action_menu.html.erb (5.6ms)
  Rendered plugins/redmine_issue_tabs/app/views/redmine_issue_tabs/_blank.html.erb (0.1ms)
  Rendered common/_tabs.html.erb (1.6ms)
  Rendered plugins/redmine_issue_tabs/app/views/hooks/redmine_issue_tabs/_rm_history_tabs.html.erb (5.5ms)
  Rendered plugins/unread_issues/app/views/hooks/unread_isues/_issue_bottom_details.html.erb (0.5ms)
  Rendered plugins/redmine_checklists/app/views/issues/_checklist.html.erb (2.6ms)
  Rendered issues/_relations.html.erb (1096.2ms)
  Rendered issues/show.html.erb within layouts/base (1268.3ms)
Completed 500 Internal Server Error in 1401ms (ActiveRecord: 99.8ms)

ActionView::Template::Error (undefined local variable or method `link_to_context_menu' for #<#<Class:0x000055bb9c2680d8>:0x00007f2b68005150>
Did you mean?  link_to_unless_current):
     8:
     9: <% if @relations.present? %>
    10: <%= form_tag({}, :data => {:cm_url => issues_context_menu_path}) do %>
    11:   <%= render_issue_relations(@issue, @relations) %>
    12: <% end %>
    13: <% end %>
    14:
  plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:84:in `block in render_issue_relations'
  plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:63:in `each'
  plugins/redmine_issue_view_columns/lib/issue_view_columns/issue_helper_patch.rb:63:in `render_issue_relations'
  app/views/issues/_relations.html.erb:11:in `block in _app_views_issues__relations_html_erb__4135833032589677690_69912249460420'
  app/views/issues/_relations.html.erb:10:in `_app_views_issues__relations_html_erb__4135833032589677690_69912249460420'
  app/views/issues/show.html.erb:115:in `_app_views_issues_show_html_erb___4428556187268442997_47132132520620'
  app/controllers/issues_controller.rb:107:in `block (2 levels) in show'
  app/controllers/issues_controller.rb:100:in `show'
  plugins/a_common_libs/lib/acl/patches/controllers/issues_controller_patch.rb:15:in `show_with_acl'
  plugins/redmine_issue_tabs/lib/redmine_issue_tabs/issues_controller_patch.rb:32:in `show_with_rit'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'


Processing by UsErrorsController#error_500 as HTML
  Parameters: {"id"=>"2276"}
  Current user: sk (id=5)
  Rendered plugins/usability/app/views/errors/error_status.html.erb (11.1ms)
Completed 500 Internal Server Error in 80ms (Views: 10.0ms | ActiveRecord: 64.8ms)

Versions:
Environment:
  Redmine version                3.4.7.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  4.2.11
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  a_common_libs                  2.5.3
  custom_menu                    1.8.5
  extra_queries                  2.3.5
  global_roles                   2.2.4
  redmine_checklists             3.1.14
  redmine_issue_dynamic_edit     0.6.7
  redmine_issue_tabs             1.3.1
  redmine_people                 1.4.0
  redmine_preview_docx           1.0.0
  redmine_thumbnail_pdf          1.0.4
  redmine_xlsx_format_issue_exporter 0.1.6
  rm_user_mentions               1.0.3
  rmplus_devtools                1.1.0
  under_construction             2.0.7
  unread_issues                  2.2.2
  usability                      2.3.8

**Comment by TrumanRu** [comment]
@kenan3008 excuse my troubling you, what about the bugfix for this issue?

**Comment by kenan3008** [comment]
@TrumanRu I've push a fix into master. Please try now. The problem was in a method link_to_context_menu which was introduced in Redmine 4 and it's not present in Redmine 3.4 that you're using.

**Comment by skillvrn** [comment]
@kenan3008 thank you! everything works

**Comment by TrumanRu** [comment]
@kenan3008 it finally works! Many thanks for great work!
